### PR TITLE
feature: show pet stats after taming and in character stats

### PR DESCRIPTION
**Pull request by boxcee**

### CODE REVIEW

**Comment by Drapersniper** [comment]
Disagree with this PR

**Comment by boxcee** [comment]
@Drapersniper, erm, wanna share why? Or. Just. Disagree?

**Comment by Drapersniper** [comment]
Pets are purposely designed in a manner in which their benefits are shown as users use them.

Showing them as soon as one is caught or through their back back removes that whole learning and trial and error aspect of the game.

**Comment by boxcee** [comment]
I would agree if the data regarding the pets wasn't publicly available (or readable). All I have to do now is STRG+F on the pets.json.

The PR is just convenience.

**Comment by Drapersniper** [comment]
I appreciate your feedback, but my stance here stays - the data is not user available unless there is trial and error and a learning experience - 
folks who wish to look at the source can but that is in no way a supported approach to the game therefore this PR which exposes the information to the end-user is not something that abides by the spirit of the game.

And as such not something I'd give an OK to.

**Pull request closed without merging**
