### PR TITLE
[3.0.0] Update - All da items and features

### PR DESCRIPTION
**Pull request by Drapersniper**
## Enhancements 
- 939 Extra pets

- 84k+ extra common items
- 84k+ extra Rare items
- 84k+ extra Epic items
- 84k+ extra Legendary items
- New 86 Set items (12 New sets)
- 3 Extra Monster attributes

## New features
- Rebirth ability at max level
- Ascended monters (Monsters with a much higher stats)
- Set Bonuses
- Pet Bonuses
- Rebirths affect loot chest drop rates
- Rebirths affects monster strength 
- Rebirths affect XP and Currency drops
- Rebirth affects crit chance
- Server Admins can set an specified Chart channel, where the chat will appear
- Repair cost at the end of adventure is based on your total amount of currency
- Rebirth Cost your full balance (With a hidden minum balance requirement to avoid people transfering balance to their alts)
- Double XP on Saturday and Sunday, 1.5x XP on Wednesday and Friday
- Stats affect skill cooldowns
- Rebirths increase Sale prices

... probably more things but cant remember right now

### CODE REVIEW

**Comment by Kevin-Mok** [comment]
The Ranger's foraging ability has no cooldown and can be spammed infinitely as of the latest commit. My best guess at a quick glance is that the cooldown isn't being properly set initially and after [in these lines](https://github.com/Drapersniper/gobcog/blob/5f2069e2793360c8f52c33678ee936a49d86400d/adventure/adventure.py#L2717-L2729)?

**Comment by aikaterna** [comment]
Loot command needs a comma after legendary and before set.

Text needs to be proper cased instead of a title case in the middle of a sentance. Examples:
* <name> Congratulations with your rebirth.
* No heroes are ready to depart in an adventure, Try again in 46 seconds
* <name>, You need to 3 rebirths to use this.

Redo the line lengths on [p]convert help text because it wraps strangely right now.

What is "panithied"? It is a mob attribute/description word that isn't a real word.

[p]adventureset restrict doesn't seem to function appropriately, ie not at all.

Was double charged for repairs on a fumble (my character appeared twice in the final wrap up message of things that happened)

Different fumble emoji pls, doesn't show on Mac or Win currently (before the character name that fumbled)

More to come as I find it.

**Comment by aikaterna** [comment]
Recieved this on a negaverse command:

```
Exception in command 'negaverse'
Traceback (most recent call last):
  File "/root/.local/share/catv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 2543, in _negaverse
    ).format(loss=humanize_number(loss), currency_name=currency_name, negachar=negachar)
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/adventure/adventure.py", line 53, in humanize_number
    return "{:,}".format(val)
ValueError: Cannot specify ',' with 's'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/share/catv3/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/root/.local/share/catv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/.local/share/catv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: Cannot specify ',' with 's'.
```

**Comment by aikaterna** [comment]
Please revert the image for the Golden Wyrm to what's specified in the current version. The image url you have from Photobucket has been blurred/obscured on the host.

**Comment by aikaterna** [comment]
Isn't the "possessed" attribute a bit extreme? Most are 0.x -> 1.2 or something similar and you have 100 as the value for the multiplier.

**Comment by aikaterna** [comment]
The results box displayed my attributes when I fumbled when it shouldn't have been displayed.

https://cdn.discordapp.com/attachments/133251234164375552/660267070596055040/Screen_Shot_2019-12-27_at_3.45.15_PM.png

The only thing that should be there in the results list is `No one!`

**Comment by Kevin-Mok** [comment]
I guess I'll add the bugs I've found here as well:
- Skill cooldowns show that they have not reset even if they have. It seems as if they work anyway, but the message showing that the skill is on cooldown is wrong.
- Buying from the cart is glitchy. Sometimes the cart will stop working completely for the user, and they cannot buy any more items.
- Taming cooldown is still broken. However, the odds for taming a pet seems to be ridiculously low and makes taming a huge chore in general. Even with taming not having any cooldown, it's still pretty painful to tame a pet.
- Sometimes a monster will give an absurd amount of EXP. This has happened a bunch of times. I've seen a Swan give 250k EXP, and another monster give 2.5 million EXP.
- Trading items to another player is broken. It doesn't matter whether the rebirths levels are lower, equal or higher.
- The `give` command is broken. I have used this command successfully on the `master` branch, but it does not seem to work with this PR.

**Comment by Drapersniper** [comment]
@Kevin-Mok 

> Skill cooldowns show that they have not reset even if they have. It seems as if they work anyway, but the message showing that the skill is on cooldown is wrong.

Can you give some examples of this to ensure i understood it properly

>Buying from the cart is glitchy. Sometimes the cart will stop working completely for the user, and they cannot buy any more items.

Do you have a reproducible scenario?

> Taming cooldown is still broken. However, the odds for taming a pet seems to be ridiculously low and makes taming a huge chore in general. Even with taming not having any cooldown, it's still pretty painful to tame a pet.

Pet taming is based on stats ... but what do you mean its broken?

> Sometimes a monster will give an absurd amount of EXP. This has happened a bunch of times. I've seen a Swan give 250k EXP, and another monster give 2.5 million EXP.

Do you have a screenshot of when this happened ? there various variables that control the XP but a low level monster should never give that much.

> Trading items to another player is broken. It doesn't matter whether the rebirths levels are lower, equal or higher.

Can you please be more descriptive as to why its broken

> The give command is broken. I have used this command successfully on the master branch, but it does not seem to work with this PR.

Same again can you please be more descriptive instead of saying its broken 



Just saying its broken doesn't really help debugging giving reproducible scenarious would be ideal

**Comment by Kevin-Mok** [comment]
@Drapersniper It seems kind of messy to discuss all the various issues in this PR thread. Would you consider enabling issues on your fork?

**Comment by Drapersniper** [comment]
@Kevin-Mok  nah its fine discussing it here ... for visibility of everyone testing it

**Comment by Kevin-Mok** [comment]
> Isn't the "possessed" attribute a bit extreme? Most are 0.x -> 1.2 or something similar and you have 100 as the value for the multiplier.

This causes the bug I mentioned:
> Sometimes a monster will give an absurd amount of EXP. This has happened a bunch of times. I've seen a Swan give 250k EXP, and another monster give 2.5 million EXP.

I've described this bug in-depth and possible fixes on [an issue on my fork](https://github.com/Kevin-Mok/gobcog/issues/1).

**Pull request closed without merging**
